name: brew test-bot

on:
  push:
    branches:
      - main
    paths:
      - 'Formula/**'
  pull_request:
    paths:
      - 'Formula/**'

jobs:
  test-bot:
    strategy:
      matrix:
        os:
          - macos-14 # arm64
          - macos-15 # arm64
          - macos-15-intel # amd64
          - macos-26 # arm64
          - macos-26-intel # amd64
        include:
          - os: ubuntu-26.04
            container: ghcr.io/homebrew/brew:main
          - os: ubuntu-26.04-arm
            container: ghcr.io/homebrew/brew:main
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
