name: brew test-bot

on:
  push:
    branches:
      - main
    paths:
      - 'Formula/**'
  pull_request:
    paths:
      - 'Formula/**'

jobs:
  test-bot:
    strategy:
      matrix:
        os:
          - ubuntu-26.04
          - ubuntu-26.04-arm
          - macos-14 # arm64
          - macos-15 # arm64
          - macos-15-intel # amd64
          - macos-26 # arm64
          - macos-26-intel # amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      # Required by homebrew
      #
      # References:
      #   https://github.com/Homebrew/brew/pull/22370
      #   https://github.com/Homebrew/brew/blob/5472a6bc/Library/Homebrew/extend/os/linux/sandbox.rb#L40-L62
      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          sudo sysctl -w user.max_user_namespaces=28633
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      # To test bunv's `conflicts_with "oven-sh/bun/bun"`
      - run: brew tap oven-sh/bun

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
